# Generated by Django 4.2.4 on 2023-08-19 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accaount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='roles',
            field=models.PositiveIntegerField(choices=[(1, 'admin'), (2, 'user')], default=1),
        ),
    ]
