# Generated by Django 4.2.4 on 2023-08-20 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accaount', '0003_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
